disp_regressor : |
  ensemble.RandomForestRegressor(
      n_estimators=200,
      max_features='sqrt',
      n_jobs=-1,
      max_depth=15,
  )

sign_classifier: |
  ensemble.RandomForestClassifier(
      n_estimators=200,
      max_features='sqrt',
      n_jobs=-1,
      max_depth=15,
  )

seed: 0

source_azimuth_column: source_position_az
source_zenith_column: source_position_zd
pointing_azimuth_column: pointing_position_az
pointing_zenith_column: pointing_position_zd

# randomly sample the data if you dont want to use the whole set
n_signal : 200000

# define th number of cross validations to perform
n_cross_validations : 5

training_variables:
  - size
  - num_pixel_in_shower
  - width
  - length
  - skewness_long
  - kurtosis_long
  - concentration_cog
  - concentration_core
  - leakage1
  - leakage2
  - slope_long
  - time_gradient_slope_long
  - photoncharge_shower_mean
  - photoncharge_shower_variance

feature_generation:
  needed_keys:
    - width
    - length
    - size
  features:
    area: width * length * @pi
    width_length: 1 - (width / length)
    size_area: size / (width * length * @pi)
