regressor: |
  ensemble.RandomForestRegressor(
    n_estimators=200,
    max_features=5,
    min_samples_split=3,
    n_jobs=-1,
    criterion='mse',
    max_depth=15,
    random_state=0,
  )


seed: 0

n_signal: 120000

log_target: False
target_name: corsika_event_header_total_energy

n_cross_validations: 5

training_variables:
  - size
  - width
  - length
  - skewness_trans
  - skewness_long
  - concentration_cog
  - concentration_core
  - concentration_one_pixel
  - concentration_two_pixel
  - leakage1
  - leakage2
  - num_islands
  - num_pixel_in_shower
  - photoncharge_shower_mean
  - photoncharge_shower_variance
  - photoncharge_shower_max


# feature generation, constants have to be prefixed with @
feature_generation:
  needed_keys:
    - size
    - width
    - length
    - cog_x
    - cog_y
  features:
    log_size: log(size)
    size_area: size / (width * length * @pi)
    area: (width * length * @pi)
    cog_r: sqrt(cog_x**2 + cog_y**2)
